// Converted using ConvPNG
// This file contains all the graphics sources for easier inclusion in a project
#ifndef tiles_gfx_H
#define tiles_gfx_H
#include <stdint.h>

#define tiles_gfx_transpcolor_index 0

extern uint8_t jumpman_walk_left0_data[210];
#define jumpman_walk_left0 ((gfx_image_t*)jumpman_walk_left0_data)
extern uint8_t jumpman_walk_left1_data[242];
#define jumpman_walk_left1 ((gfx_image_t*)jumpman_walk_left1_data)
extern uint8_t jumpman_walk_left2_data[242];
#define jumpman_walk_left2 ((gfx_image_t*)jumpman_walk_left2_data)
extern uint8_t jumpman_jump_left_data[242];
#define jumpman_jump_left ((gfx_image_t*)jumpman_jump_left_data)
extern uint8_t jumpman_slide_left_data[242];
#define jumpman_slide_left ((gfx_image_t*)jumpman_slide_left_data)
extern uint8_t jumpman_walk_right0_data[226];
#define jumpman_walk_right0 ((gfx_image_t*)jumpman_walk_right0_data)
extern uint8_t jumpman_walk_right1_data[242];
#define jumpman_walk_right1 ((gfx_image_t*)jumpman_walk_right1_data)
extern uint8_t jumpman_walk_right2_data[242];
#define jumpman_walk_right2 ((gfx_image_t*)jumpman_walk_right2_data)
extern uint8_t jumpman_jump_right_data[242];
#define jumpman_jump_right ((gfx_image_t*)jumpman_jump_right_data)
extern uint8_t jumpman_hammer_left0_data[242];
#define jumpman_hammer_left0 ((gfx_image_t*)jumpman_hammer_left0_data)
extern uint8_t jumpman_hammer_left1_data[242];
#define jumpman_hammer_left1 ((gfx_image_t*)jumpman_hammer_left1_data)
extern uint8_t jumpman_hammer_left2_data[242];
#define jumpman_hammer_left2 ((gfx_image_t*)jumpman_hammer_left2_data)
extern uint8_t jumpman_hammer_left3_data[242];
#define jumpman_hammer_left3 ((gfx_image_t*)jumpman_hammer_left3_data)
extern uint8_t jumpman_hammer_left4_data[242];
#define jumpman_hammer_left4 ((gfx_image_t*)jumpman_hammer_left4_data)
extern uint8_t jumpman_hammer_left5_data[242];
#define jumpman_hammer_left5 ((gfx_image_t*)jumpman_hammer_left5_data)
extern uint8_t jumpman_hammer_right0_data[242];
#define jumpman_hammer_right0 ((gfx_image_t*)jumpman_hammer_right0_data)
extern uint8_t jumpman_hammer_right1_data[242];
#define jumpman_hammer_right1 ((gfx_image_t*)jumpman_hammer_right1_data)
extern uint8_t jumpman_hammer_right2_data[242];
#define jumpman_hammer_right2 ((gfx_image_t*)jumpman_hammer_right2_data)
extern uint8_t jumpman_hammer_right3_data[242];
#define jumpman_hammer_right3 ((gfx_image_t*)jumpman_hammer_right3_data)
extern uint8_t jumpman_hammer_right4_data[242];
#define jumpman_hammer_right4 ((gfx_image_t*)jumpman_hammer_right4_data)
extern uint8_t jumpman_hammer_right5_data[242];
#define jumpman_hammer_right5 ((gfx_image_t*)jumpman_hammer_right5_data)
extern uint8_t jumpman_slide_right_data[242];
#define jumpman_slide_right ((gfx_image_t*)jumpman_slide_right_data)
extern uint8_t jumpman_climb_left0_data[242];
#define jumpman_climb_left0 ((gfx_image_t*)jumpman_climb_left0_data)
extern uint8_t jumpman_climb_left1_data[242];
#define jumpman_climb_left1 ((gfx_image_t*)jumpman_climb_left1_data)
extern uint8_t jumpman_climb_left2_data[242];
#define jumpman_climb_left2 ((gfx_image_t*)jumpman_climb_left2_data)
extern uint8_t jumpman_climb_right0_data[242];
#define jumpman_climb_right0 ((gfx_image_t*)jumpman_climb_right0_data)
extern uint8_t jumpman_climb_right1_data[242];
#define jumpman_climb_right1 ((gfx_image_t*)jumpman_climb_right1_data)
extern uint8_t jumpman_climb_right2_data[242];
#define jumpman_climb_right2 ((gfx_image_t*)jumpman_climb_right2_data)
extern uint8_t jumpman_standing_data[242];
#define jumpman_standing ((gfx_image_t*)jumpman_standing_data)
extern uint8_t jumpman_dead0_data[258];
#define jumpman_dead0 ((gfx_image_t*)jumpman_dead0_data)
extern uint8_t jumpman_dead1_data[258];
#define jumpman_dead1 ((gfx_image_t*)jumpman_dead1_data)
extern uint8_t jumpman_dead2_data[258];
#define jumpman_dead2 ((gfx_image_t*)jumpman_dead2_data)
extern uint8_t jumpman_dead3_data[258];
#define jumpman_dead3 ((gfx_image_t*)jumpman_dead3_data)
extern uint8_t jumpman_dead4_data[258];
#define jumpman_dead4 ((gfx_image_t*)jumpman_dead4_data)
extern uint8_t jumpman_dead5_data[258];
#define jumpman_dead5 ((gfx_image_t*)jumpman_dead5_data)
extern uint8_t life_data[58];
#define life ((gfx_image_t*)life_data)
extern uint8_t barrel_standing_data[162];
#define barrel_standing ((gfx_image_t*)barrel_standing_data)
extern uint8_t barrel_rolling_N0_data[122];
#define barrel_rolling_N0 ((gfx_image_t*)barrel_rolling_N0_data)
extern uint8_t barrel_rolling_N1_data[122];
#define barrel_rolling_N1 ((gfx_image_t*)barrel_rolling_N1_data)
extern uint8_t barrel_rolling_N2_data[122];
#define barrel_rolling_N2 ((gfx_image_t*)barrel_rolling_N2_data)
extern uint8_t barrel_rolling_N3_data[122];
#define barrel_rolling_N3 ((gfx_image_t*)barrel_rolling_N3_data)
extern uint8_t barrel_rolling_B0_data[122];
#define barrel_rolling_B0 ((gfx_image_t*)barrel_rolling_B0_data)
extern uint8_t barrel_rolling_B1_data[122];
#define barrel_rolling_B1 ((gfx_image_t*)barrel_rolling_B1_data)
extern uint8_t barrel_rolling_B2_data[122];
#define barrel_rolling_B2 ((gfx_image_t*)barrel_rolling_B2_data)
extern uint8_t barrel_rolling_B3_data[122];
#define barrel_rolling_B3 ((gfx_image_t*)barrel_rolling_B3_data)
extern uint8_t barrel_ladder_N0_data[162];
#define barrel_ladder_N0 ((gfx_image_t*)barrel_ladder_N0_data)
extern uint8_t barrel_ladder_N1_data[162];
#define barrel_ladder_N1 ((gfx_image_t*)barrel_ladder_N1_data)
extern uint8_t barrel_ladder_B0_data[162];
#define barrel_ladder_B0 ((gfx_image_t*)barrel_ladder_B0_data)
extern uint8_t barrel_ladder_B1_data[162];
#define barrel_ladder_B1 ((gfx_image_t*)barrel_ladder_B1_data)
extern uint8_t kong_standing_data[1282];
#define kong_standing ((gfx_image_t*)kong_standing_data)
extern uint8_t kong_holding_data[1282];
#define kong_holding ((gfx_image_t*)kong_holding_data)
extern uint8_t kong_right_data[1378];
#define kong_right ((gfx_image_t*)kong_right_data)
extern uint8_t kong_left_data[1378];
#define kong_left ((gfx_image_t*)kong_left_data)
extern uint8_t kong_arm_left_data[1474];
#define kong_arm_left ((gfx_image_t*)kong_arm_left_data)
extern uint8_t kong_arm_right_data[1474];
#define kong_arm_right ((gfx_image_t*)kong_arm_right_data)
extern uint8_t kong_climbing_left0_data[1190];
#define kong_climbing_left0 ((gfx_image_t*)kong_climbing_left0_data)
extern uint8_t kong_climbing_left1_data[1370];
#define kong_climbing_left1 ((gfx_image_t*)kong_climbing_left1_data)
extern uint8_t kong_climbing_right0_data[1190];
#define kong_climbing_right0 ((gfx_image_t*)kong_climbing_right0_data)
extern uint8_t kong_climbing_right1_data[1550];
#define kong_climbing_right1 ((gfx_image_t*)kong_climbing_right1_data)
extern uint8_t kong_goofy_data[1474];
#define kong_goofy ((gfx_image_t*)kong_goofy_data)
extern uint8_t oilcan_sprite_data[258];
#define oilcan_sprite ((gfx_image_t*)oilcan_sprite_data)
extern uint8_t girder_data[66];
#define girder ((gfx_image_t*)girder_data)
extern uint8_t girder_circle_data[66];
#define girder_circle ((gfx_image_t*)girder_circle_data)
extern uint8_t conveyor_tile_data[66];
#define conveyor_tile ((gfx_image_t*)conveyor_tile_data)
extern uint8_t x_tile_data[66];
#define x_tile ((gfx_image_t*)x_tile_data)
extern uint8_t ladder_data[66];
#define ladder ((gfx_image_t*)ladder_data)
extern uint8_t rivet_data[74];
#define rivet ((gfx_image_t*)rivet_data)
extern uint8_t pulley_left0_data[112];
#define pulley_left0 ((gfx_image_t*)pulley_left0_data)
extern uint8_t pulley_left1_data[112];
#define pulley_left1 ((gfx_image_t*)pulley_left1_data)
extern uint8_t pulley_left2_data[112];
#define pulley_left2 ((gfx_image_t*)pulley_left2_data)
extern uint8_t pulley_right0_data[112];
#define pulley_right0 ((gfx_image_t*)pulley_right0_data)
extern uint8_t pulley_right1_data[112];
#define pulley_right1 ((gfx_image_t*)pulley_right1_data)
extern uint8_t pulley_right2_data[112];
#define pulley_right2 ((gfx_image_t*)pulley_right2_data)
extern uint8_t pie_sprite_data[130];
#define pie_sprite ((gfx_image_t*)pie_sprite_data)
extern uint8_t fire0_data[258];
#define fire0 ((gfx_image_t*)fire0_data)
extern uint8_t fire1_data[258];
#define fire1 ((gfx_image_t*)fire1_data)
extern uint8_t fire2_data[258];
#define fire2 ((gfx_image_t*)fire2_data)
extern uint8_t fire3_data[258];
#define fire3 ((gfx_image_t*)fire3_data)
extern uint8_t firefox_left0_data[242];
#define firefox_left0 ((gfx_image_t*)firefox_left0_data)
extern uint8_t firefox_left1_data[242];
#define firefox_left1 ((gfx_image_t*)firefox_left1_data)
extern uint8_t firefox_right0_data[242];
#define firefox_right0 ((gfx_image_t*)firefox_right0_data)
extern uint8_t firefox_right1_data[242];
#define firefox_right1 ((gfx_image_t*)firefox_right1_data)
extern uint8_t fireball_left0_data[258];
#define fireball_left0 ((gfx_image_t*)fireball_left0_data)
extern uint8_t fireball_left1_data[258];
#define fireball_left1 ((gfx_image_t*)fireball_left1_data)
extern uint8_t fireball_right0_data[258];
#define fireball_right0 ((gfx_image_t*)fireball_right0_data)
extern uint8_t fireball_right1_data[258];
#define fireball_right1 ((gfx_image_t*)fireball_right1_data)
extern uint8_t text_bonus_data[167];
#define text_bonus ((gfx_image_t*)text_bonus_data)
extern uint8_t num100_data[107];
#define num100 ((gfx_image_t*)num100_data)
extern uint8_t num200_data[107];
#define num200 ((gfx_image_t*)num200_data)
extern uint8_t num300_data[107];
#define num300 ((gfx_image_t*)num300_data)
extern uint8_t num500_data[107];
#define num500 ((gfx_image_t*)num500_data)
extern uint8_t num800_data[107];
#define num800 ((gfx_image_t*)num800_data)
extern uint8_t parasol_data[242];
#define parasol ((gfx_image_t*)parasol_data)
extern uint8_t purse_data[83];
#define purse ((gfx_image_t*)purse_data)
extern uint8_t hat_data[122];
#define hat ((gfx_image_t*)hat_data)
extern uint8_t hammer_left0_data[92];
#define hammer_left0 ((gfx_image_t*)hammer_left0_data)
extern uint8_t hammer_left1_data[155];
#define hammer_left1 ((gfx_image_t*)hammer_left1_data)
extern uint8_t hammer_right0_data[92];
#define hammer_right0 ((gfx_image_t*)hammer_right0_data)
extern uint8_t hammer_right1_data[155];
#define hammer_right1 ((gfx_image_t*)hammer_right1_data)
extern uint8_t pauline_left0_data[354];
#define pauline_left0 ((gfx_image_t*)pauline_left0_data)
extern uint8_t pauline_left1_data[354];
#define pauline_left1 ((gfx_image_t*)pauline_left1_data)
extern uint8_t pauline_left2_data[354];
#define pauline_left2 ((gfx_image_t*)pauline_left2_data)
extern uint8_t pauline_right0_data[354];
#define pauline_right0 ((gfx_image_t*)pauline_right0_data)
extern uint8_t pauline_right1_data[354];
#define pauline_right1 ((gfx_image_t*)pauline_right1_data)
extern uint8_t pauline_right2_data[354];
#define pauline_right2 ((gfx_image_t*)pauline_right2_data)
extern uint8_t help_left_data[186];
#define help_left ((gfx_image_t*)help_left_data)
extern uint8_t help_right_data[194];
#define help_right ((gfx_image_t*)help_right_data)
extern uint8_t heart_data[197];
#define heart ((gfx_image_t*)heart_data)
extern uint8_t heart_broken_data[210];
#define heart_broken ((gfx_image_t*)heart_broken_data)
extern uint8_t circle0_data[170];
#define circle0 ((gfx_image_t*)circle0_data)
extern uint8_t circle1_data[82];
#define circle1 ((gfx_image_t*)circle1_data)
extern uint8_t circle2_data[38];
#define circle2 ((gfx_image_t*)circle2_data)
extern uint8_t burst_data[226];
#define burst ((gfx_image_t*)burst_data)
extern uint8_t bouncer0_data[182];
#define bouncer0 ((gfx_image_t*)bouncer0_data)
extern uint8_t bouncer1_data[178];
#define bouncer1 ((gfx_image_t*)bouncer1_data)
extern uint8_t elevator_platform_data[130];
#define elevator_platform ((gfx_image_t*)elevator_platform_data)
extern uint8_t receptable_bottom_data[258];
#define receptable_bottom ((gfx_image_t*)receptable_bottom_data)
extern uint8_t receptable_top_data[258];
#define receptable_top ((gfx_image_t*)receptable_top_data)
extern uint8_t retracting_ladder_sprite_data[162];
#define retracting_ladder_sprite ((gfx_image_t*)retracting_ladder_sprite_data)
extern uint16_t tiles_gfx_pal[27];

#endif
